apiVersion: apps/v1
kind: Deployment
metadata:
    name: argocd-repo-server
spec:
    template:
      spec:
        containers:
        - name: argocd-repo-server
          env:
          - name: CLOUDSDK_CONFIG
            value: "/home/argocd/.config/gcloud"