apiVersion: apps/v1
kind: Deployment
metadata:
    name: argocd-application-controller
spec:
    template:
      spec:
        containers:
        - name: argocd-application-controller
          image: argocd:latest
          imagePullPolicy: Never