apiVersion: kustomize.config.k8s.io/v1beta1
bases:
# - kustomize/istio-crds/
# - kustomize/istio-install/
- kustomize/cluster-local-gateway/
# - kustomize/istio/
- kustomize/add-anonymous-user-filter/
- kustomize/application-crds/
- kustomize/application/
- kustomize/cert-manager-crds/
- kustomize/cert-manager-kube-system-resources/
- kustomize/cert-manager/
- kustomize/metacontroller/
- kustomize/argo/
- kustomize/kubeflow-roles/
- kustomize/centraldashboard/
- kustomize/bootstrap/
- kustomize/webhook/
- kustomize/jupyter-web-app/
- kustomize/spark-operator/
- kustomize/metadata/
- kustomize/notebook-controller/
- kustomize/pytorch-job-crds/
- kustomize/pytorch-operator/
- kustomize/knative-crds/
- kustomize/knative-install/
- kustomize/kfserving-crds/
- kustomize/kfserving-install/
- kustomize/spartakus/
- kustomize/tensorboard/
- kustomize/tf-job-crds/
- kustomize/tf-job-operator/
- kustomize/katib-crds/
- kustomize/katib-controller/
- kustomize/api-service/
- kustomize/minio/
- kustomize/mysql/
- kustomize/persistent-agent/
- kustomize/pipelines-runner/
- kustomize/pipelines-ui/
- kustomize/pipelines-viewer/
- kustomize/scheduledworkflow/
- kustomize/pipeline-visualization-service/
- kustomize/profiles/
- kustomize/seldon-core-operator/

kind: Kustomization
