apiVersion: apps/v1
kind: Deployment
metadata:
    name: seldon-controller-manager
    namespace: 'ml-serving'
spec:
    template:
      spec:
        containers:
        - args:
          - --namespace=ml-serving-sandbox
          - --enable-leader-election
          - --webhook-port=8443
          name: manager